run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - gosimple
    - unused
    - staticcheck
    - revive
    - goconst
    - gocognit

linters-settings:
  gocognit:
    min-complexity: 15
  revive:
    rules:
      - name: exported
        disabled: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0